### PR TITLE
add method for ruby logger compat

### PR DESCRIPTION
**Pull request by chrisp**
WIP

### CODE REVIEW

**Comment by brixen** [comment]
@chrisp thanks! Any reason not to merge this?

**Comment by chrisp** [comment]
Still trying to get a good test on this.  I haven't been able to reproduce the case where a call to the add method fails in master but not on this.

**Comment by brixen** [comment]
@chrisp I pulled your changes locally and reverted the lib change and ran the specs, which fail as expected. I'm going to merge and release and we can iterate if you're still seeing issues when using the gem.

**Comment by chrisp** [comment]
@brixen Sounds good - thanks!

**Pull request merged**
